item_type = {
	{ "ETC", 0 },
	{ "ARMOR", 1 },
	{ "CARD", 2 },
	{ "USEABLE", 3 },
	{ "CUBE", 4 },
	{ "CHARM", 5 },
	{ "USE", 6 },
	{ "SOULSTONE", 7 },
	{ "CREATURE", 8 }
}

item_group = {
	{ "ETC", 0 },
	{ "WEAPON", 1 },
	{ "ARMOR", 2 },
	{ "SHIELD", 3 },
	{ "HELM", 4 },
	{ "GLOVE", 5 },
	{ "BOOTS", 6 },
	{ "BELT", 7 },
	{ "MANTLE", 8 },
	{ "ACCESSORY", 9 },
	{ "SKILLCARD", 10 },
	{ "ITEMCARD", 11 },
	{ "SPELLCARD", 12 },
	{ "SUMMONCARD", 13 },
	{ "FACE", 15 },
	{ "UNDERWEAR", 16 },  
	{ "BAG", 17 },
	{ "PETCAGE", 18 },	
	{ "STRIKE_CUBE", 21 },
	{ "DEFENCE_CUBE", 22 },
	{ "SKILL_CUBE", 23 },
	{ "CASH_ITEM", 80 },
	{ "SOULSTONE", 93 },
	{ "BULLET", 98 },
	{ "USEABLE", 99 },
	{ "DECO", 110 },
	{ "RIDING", 120 },
	{ "ARTIFACT", 130 },	
	{ "BOSSCARD", 140 }
}

item_class = {
	{ "ETC", 0 },
	{ "DOUBLE_AXE", 95 },
	{ "DOUBLE_SWORD", 96 },
	{ "DOUBLE_DAGGER", 98 },
	{ "EVERY_WEAPON", 99 },
	{ "ETCWEAPON", 100 },	
	{ "ONEHAND_SWORD", 101 },		
	{ "TWOHAND_SWORD", 102 },	
	{ "DAGGER", 103 },
	{ "TWOHAND_SPEAR", 104 },		
	{ "TWOHAND_AXE", 105 },		
	{ "ONEHAND_MACE", 106 },		
	{ "TWOHAND_MACE", 107 },		
	{ "HEAVY_BOW", 108 },
	{ "LIGHT_BOW", 109 },	
	{ "CROSSBOW", 110 },	
	{ "ONEHAND_STAFF", 111 },	
	{ "TWOHAND_STAFF", 112 },	
	{ "ONEHAND_AXE", 113 },
	{ "DOUBLE_WEAPON", 199 },
	{ "ARMOR", 200 },
	{ "FIGHTER_ARMOR", 201 },		
	{ "HUNTER_ARMOR", 202 },		
	{ "MAGICIAN_ARMOR", 203 },	
	{ "SUMMONER_ARMOR", 204 },	
	{ "SHIELD", 210 },
	{ "HELM", 220 },	
	{ "BOOTS", 230 },	
	{ "FIGHTER_BOOTS", 231 },	
	{ "HUNTER_BOOTS ", 232 },
	{ "MAGICIAN_BOOTS", 233 },
	{ "SUMMONER_BOOTS", 234 },	
	{ "GLOVE", 240 },		
	{ "FIGHTER_GLOVE", 241 },	
	{ "HUNTER_GLOVE ", 242 },	
	{ "MAGICIAN_GLOVE", 243 },
	{ "SUMMONER_GLOVE", 244 },	
	{ "BELT", 250 },
	{ "FIGHTER_BELT ", 251 },		
	{ "HUNTER_BELT  ", 252 },	
	{ "MAGICIAN_BELT", 253 },
	{ "SUMMONER_BELT", 254 },
	{ "MANTLE", 260 },
	{ "FIGHTER_MANTLE ", 261 },	
	{ "HUNTER_MANTLE  ", 262 },
	{ "MAGICIAN_MANTLE", 263 },
	{ "SUMMONER_MANTLE", 264 },
	{ "ETC_ACCESSORY", 300 },
	{ "RING", 301 },
	{ "EARRING", 302 },
	{ "ARMULET", 303 },
	{ "EYEGLASS", 304 },	
	{ "MASK", 305 },
	{ "CUBE", 306 },
	{ "BOOST_CHIP", 400 },
	{ "SOULSTONE", 401 },
	{ "CRACKER", 402 },
	{ "FARM_TICKET", 403 },
	{ "USE_CASH_ITEM", 502 },
	{ "DECO_WEAPON", 600 },
	{ "DECO_SHIELD", 601 },
	{ "DECO_ARMOR", 602 },
	{ "DECO_HELM	", 603 },
	{ "DECO_GLOVE", 604 },
	{ "DECO_BOOTS", 605 },
	{ "DECO_MALTLE", 606 },
	{ "DECO_SHOULDER", 607 },
	{ "DECO_HAIR", 608 },
	{ "DECO_ONEHAND_SWORD", 609 },
	{ "DECO_TWOHAND_SWORD", 610 },
	{ "DECO_DAGGER", 611 },
	{ "DECO_TWOHAND_SPEAR", 612 },
	{ "DECO_TWOHAND_AXE	", 613 },
	{ "DECO_ONEHAND_MACE	", 614 },	
	{ "DECO_TWOHAND_MACE	", 615 },		
	{ "DECO_HEAVY_BOW", 616 },	
	{ "DECO_LIGHT_BOW", 617 },
	{ "DECO_CROSSBOW", 618 },	
	{ "DECO_ONEHAND_STAFF", 619 },	
	{ "DECO_TWOHAND_STAFF", 620 },	
	{ "DECO_ONEHAND_AXE", 621 }
}

item_wear_type = {
	{ "CANTWEAR", -1 },
	{ "NONE", -1 },
	{ "STORAGE", -2 },
	{ "WEAPON", 0 },
	{ "SHIELD", 1 },
	{ "ARMOR", 2 },
	{ "HELM", 3 },
	{ "GLOVE", 4 },	
	{ "BOOTS", 5 },
	{ "BELT", 6 },
	{ "MANTLE", 7 },	
	{ "ARMULET", 8 },
	{ "RING", 9 },	
	{ "EAR", 11 },
	{ "FACE", 12 },	
	{ "DECO_HAIR", 13 },	
	{ "DECO_WEAPON", 14 },	
	{ "DECO_SHIELD", 15 },
	{ "DECO_ARMOR", 16 },
	{ "DECO_HELM", 17 },
	{ "DECO_GLOVE", 18 },
	{ "DECO_BOOTS", 19 },
	{ "DECO_MANTLE", 20 },
	{ "DECO_SHOULDER", 21 },
	{ "RIDE_ITEM", 22 },
	{ "BAG_SLOT", 23 },
	{ "SWAP_WEAPON", 24 },	
	{ "SWAP_SHIELD", 25 },
	{ "SWAP_DECO_WEAPON", 26 },	
	{ "SWAP_DECO_SHIELD", 27 },
	{ "BELT_SLOT", 198 },
	{ "DECO_TWOHAND", 199 },
	{ "EAR_EYE", 90 },
	{ "EAR_MOUTH", 91 },
	{ "EYE_MOUTH", 92 },
	{ "EYE_EAR_MOUTH", 93 },
	{ "TWOFINGER_RING", 94 },
	{ "TWOHAND", 99 },
	{ "SKILL", 100 },
	{ "SUMMON_ONLY", 200 },	
	{ "SECOND_RING", 10 },
	{ "RIGHTHAND", 0 },
	{ "LEFTHAND", 1 },
	{ "BULLET", 1 },
	{ "BELT00", 1000 },
	{ "BELT01", 1001 },
	{ "BELT02", 1002 },
	{ "BELT03", 1003 },
	{ "BELT04", 1004 },
	{ "BELT05", 1005 }
}

item_effect_passive = {
	{ "ATTACK_POINT", 11 },	
	{ "MAGIC_POINT", 12 },
	{ "ACCURACY", 13 },
	{ "ATTACK_SPEED", 14 },	
	{ "DEFENCE", 15 },
	{ "MAGIC_DEFENCE", 16 },	
	{ "AVOID", 17 },
	{ "MOVE_SPEED", 18 },	
	{ "BLOCK_CHANGE", 19 },	
	{ "CARRY_WEIGHT", 20 },
	{ "BLOCK_DEFENCE", 21 },	
	{ "CASTING_SPEED", 22 },
	{ "MAGIC_ACCURACY", 23 },
	{ "MAGIC_AVOID", 24 },
	{ "COOLTIME_SPEED", 25 },
	{ "BELT_SLOT", 26 },
	{ "MAX_CHAOS", 27 },
	{ "MAX_HP", 30 },
	{ "MAX_MP=",31 },
	{ "BOW_INTERVAL", 34 },
	{ "MP_REGEN_POINT", 33 },
	{ "TAMED_ITEM", 95 },
	{ "INC_PARAMETER_A", 96 },
	{ "INC_PARAMETER_B", 97 },
	{ "AMP_PARAMETER_A", 98 },
	{ "AMP_PARAMETER_B", 99 }
}

item_decrease_type = {
	{ "PERMANENT", 0 },
	{ "DECREASE_ON_GAME", 1 },
	{ "DECREASE_ALWAYS", 2 }
}