tableName = "CharacterMotion"
fileName = "db_charactermotion(ascii)"

fields = {
	{"motion_id", INT32},
	{"race_id", INT32},
	{"sex", INT32},
	{"file_name", STRING, length=256},
	{"frame_length", INT32},
	{"play_speed", INT32},
	{"graphic_effect_file_ID", INT32},
	{"graphic_effect_speed_type", INT32},
	{"graphic_effect_position", INT32},
	{"graphic_effect_follow", BYTE, length=1},
	{"graphic_effect_disappear", BYTE, length=1},
	{"padding0", INT16, show=0},
	{"sound_file_ID", INT32},
	{"sound_volumn", INT32},
	{"sound_play_probability", INT32},
	{"sound_timing", INT32},
	{"sound_reverb_apply", BYTE, length=1},
	{"sound_filter_apply", BYTE, length=1},
	{"sound_stereo_apply", BYTE, length=1},
	{"padding1", BYTE, length=1, show=0},
	{"fx_id", INT32},
	{"fx_timing", INT32},
	{"fx_position", INT32},
	{"fx_play_speed", INT32},
	{"event01_id", INT32},
	{"event01_timing", INT32},
	{"event02_id", INT32},
	{"event02_timing", INT32},
	{"event03_id", INT32},
	{"event03_timing", INT32},
	{"event04_id", INT32},
	{"event04_timing", INT32},
	{"event05_id", INT32},
	{"event05_timing", INT32},
	{"event06_id", INT32},
	{"event06_timing", INT32},
	{"event07_id", INT32},
	{"event07_timing", INT32},
	{"event08_id", INT32},
	{"event08_timing", INT32},
	{"event09_id", INT32},
	{"event09_timing", INT32},
	{"event10_id", INT32},
	{"event10_timing", INT32},
}