tableName = "FieldPropResource"
fileName = "db_fieldpropresource(ascii).rdb"

fields = {
	{"id", INT32},
	{"text_id", INT32},
	{"tooltip_id", INT32},
	{"type", INT32},
	{"local_flag", INT32},
	{"casting_time", INT32},
	{"use_count", INT32},
	{"regen_time", INT32},
	{"life_time", INT32},
	{"casting_range", SINGLE},
	{"target_fx_size", SINGLE},
	{"limit_min_level", INT32},
	{"limit_max_level", INT32},
	{"limit_deva", BYTE},
	{"limit_asura", BYTE},
	{"limit_gaia", BYTE},
	{"limit_fighter", BYTE},
	{"limit_hunter", BYTE},
	{"limit_magician", BYTE},
	{"limit_summoner", BYTE},
	{"limit_job", INT32},
	{"activation_condition", INT32},
	{"activation_value1", INT32},
	{"activation_value2", INT32},
	{"activation2_condition", INT32},
	{"activation2_value1", INT32},
	{"activation2_value2", INT32},
	{"activate_id", INT32},
	{"drop_item_id_00", INT32},
	{"drop_item_ratio_00", INT32},
	{"drop_item_count_min_00", INT32},
	{"drop_item_count_max_00", INT32},
	{"drop_item_level_min_00", INT32},
	{"drop_item_level_max_00", INT32},
	{"drop_item_id_01", INT32},
	{"drop_item_ratio_01", INT32},
	{"drop_item_count_min_01", INT32},
	{"drop_item_count_max_01", INT32},
	{"drop_item_level_min_01", INT32},
	{"drop_item_level_max_01", INT32},
	{"script_text", STRING, length=256},
	{"file_name", STRING, length=256},
	{"terrain_check", INT32},
	{"worldmap_check_type", INT16}
}