require 'ItemEnums72'

tableName = "ItemResource"
fileName = "db_item.rdb"

fields = {
	{"id", INT32},
	{"name_id", INT32},
	{"type", INT32, flag=ENUM, opt={ "item_type" }}, -- The item_type enum is defined in the above required /Enums/ItemEnums72.lua
	{"group", INT32, flag=ENUM, opt={ "item_group" }},
	{"class", INT32, flag=ENUM, opt={ "item_class" }},
	{"set_id", INT32},
	{"set_part_flag", INT32},
	{"grade", BYTE},
	{"rank", INT32},
	{"level", INT32},
	{"enhance", INT32},
	{"socket", INT32},
	{"status_flag", INT32},
	{"use_min_level", INT32},
	{"use_max_level", INT32},
	{"target_min_level", INT32},
	{"target_max_level", INT32},
	{"range", DECIMAL},
	{"weight", SINGLE},
	{"price", INT32},
	{"huntaholic_point", INT32},
	{"ethereal_durability", INT32},
	{"endurance", INT32},
	{"wear_type", INT32, flag=ENUM, opt={ "item_wear_type" }},
	{"limit_bits", BIT_VECTOR, show=0 },
	{"limit_deva", BIT_FROM_VECTOR, dependency="limit_bits", bit_position=2},
	{"limit_asura", BIT_FROM_VECTOR, dependency="limit_bits", bit_position=3},
	{"limit_gaia", BIT_FROM_VECTOR, dependency="limit_bits", bit_position=4},
	{"limit_fighter", BIT_FROM_VECTOR, dependency="limit_bits", bit_position=10},
	{"limit_hunter", BIT_FROM_VECTOR, dependency="limit_bits", bit_position=11},
	{"limit_magician", BIT_FROM_VECTOR, dependency="limit_bits", bit_position=12},
	{"limit_summoner", BIT_FROM_VECTOR, dependency="limit_bits", bit_position=13},
	{"item_use_flag", INT32, flag=BIT_FLAG, opt={ "use_flags_under_81" }},
	{"item_use_flag", INT32, show=0}, -- Use the same name so engine will copy shown value
	{"material", INT32},
	{"summon_id", INT32},
	{"throw_range", DECIMAL},
	{"base_type_0", INT16},
	{"base_type_1", INT16},
	{"base_type_2", INT16},
	{"base_type_3", INT16},
	{"base_var1_0", DOUBLE},
	{"base_var1_1", DOUBLE},
	{"base_var1_2", DOUBLE},
	{"base_var1_3", DOUBLE},
	{"base_var2_0", DOUBLE},
	{"base_var2_1", DOUBLE},
	{"base_var2_2", DOUBLE},
	{"base_var2_3", DOUBLE},
	{"opt_type_0", INT16, flag=ENUM, opt={ "item_effect_passive" }},
	{"opt_type_1", INT16, flag=ENUM, opt={ "item_effect_passive" }},
	{"opt_type_2", INT16, flag=ENUM, opt={ "item_effect_passive" }},
	{"opt_type_3", INT16, flag=ENUM, opt={ "item_effect_passive" }},
	{"opt_var1_0", DOUBLE},
	{"opt_var1_1", DOUBLE},
	{"opt_var1_2", DOUBLE},
	{"opt_var1_3", DOUBLE},
	{"opt_var2_0", DOUBLE},
	{"opt_var2_1", DOUBLE},
	{"opt_var2_2", DOUBLE},
	{"opt_var2_3", DOUBLE},
	{"effect_id", INT32},
	{"enhance_0_id", INT16},
	{"enhance_1_id", INT16},
	{"enhance_0_01", SINGLE},
	{"enhance_0_02", SINGLE},
	{"enhance_0_03", SINGLE},
	{"enhance_0_04", SINGLE},
	{"enhance_1_01", SINGLE},
	{"enhance_1_02", SINGLE},
	{"enhance_1_03", SINGLE},
	{"enhance_1_04", SINGLE},
	{"skill_id", INT32},
	{"state_id", INT32},
	{"state_level", INT32},
	{"state_time", INT32},
	{"state_type", BYTE, default=0, show=0},
	{"cool_time", INT32},
	{"cool_time_group", INT16},
	{"available_period", INT32},
	{"decrease_type", INT16, flag=ENUM, opt={ "item_decrease_type" }},
	{"unknown2", INT16, default=49, show=0},
	{"model_type_dem", INT32, flag=BIT_FLAG, opt={ "item-model_type" }},
	{"model_type_def", INT32, flag=BIT_FLAG, opt={ "item-model_type" }},
	{"model_type_asm", INT32, flag=BIT_FLAG, opt={ "item-model_type" }},
	{"model_type_asf", INT32, flag=BIT_FLAG, opt={ "item-model_type" }},
	{"model_type_gam", INT32, flag=BIT_FLAG, opt={ "item-model_type" }},
	{"model_type_gaf", INT32, flag=BIT_FLAG, opt={ "item-model_type" }},
	{"deco_model_change", BYTE},
	{"model_00", STRING, length=256},
	{"model_01", STRING, length=256},
	{"model_02", STRING, length=256},
	{"model_03", STRING, length=256},
	{"model_04", STRING, length=256},
	{"model_05", STRING, length=256},
	{"model_06", STRING, length=256},
	{"model_07", STRING, length=256},
	{"model_08", STRING, length=256},
	{"model_09", STRING, length=256},
	{"model_10", STRING, length=256},
	{"model_11", STRING, length=256},
	{"model_12", STRING, length=256},
	{"model_13", STRING, length=256},
	{"model_14", STRING, length=256},
	{"model_15", STRING, length=256},
	{"model_16", STRING, length=256},
	{"model_17", STRING, length=256},
	{"texture_filename", STRING, length=256},
	{"drop_type", STRING, length=256},
	{"unkCatValue", STRING, length=3, default="Cat", show=0},
	{"icon_id", INT32},
	{"icon_file_name", STRING, length=256},
	{"script_text", STRING, length=512},
	{"tooltip_id", INT32}
}