tableName = "NpcResource"
fileName = "db_npcresource(ascii).rdb"

fields =
{
	{"id", INT32},
	{"text_id", INT32},
	{"name_text_id", INT32},
	{"race_id", INT32},
	{"sexsual_id", INT32},
	{"x", INT32},
	{"y", INT32},
	{"z", INT32},
	{"face", INT32},
	{"local_flag", INT32},
	{"is_periodic", BYTE},
	{"begin_of_period", DATETIME},
	{"end_of_period", DATETIME},
	{"face_x", INT32},
	{"face_y", INT32},
	{"face_z", INT32},
	{"model_file", STRING, length=256},
	{"hair_id", INT32},
	{"face_id", INT32},
	{"body_id", INT32},
	{"weapon_item_id", INT32},
	{"shield_item_id", INT32},
	{"clothes_item_id", INT32},
	{"helm_item_id", INT32},
	{"gloves_item_id", INT32},
	{"boots_item_id", INT32},
	{"belt_item_id", INT32},
	{"mantle_item_id", INT32},
	{"necklace_item_id", INT32},
	{"earring_item_id", INT32},
	{"ring1_item_id", INT32},
	{"ring2_item_id", INT32},
	{"motion_id", INT32},
	{"is_roam", INT32},
	{"roaming_id", INT32},
	{"standard_walk_speed", INT32},
	{"standard_run_speed", INT32},
	{"walk_speed", INT32},
	{"run_speed", INT32},
	{"attackable", INT32},
	{"offensive_type", INT32},
	{"spawn_type", INT32},
	{"chase_range", INT32},
	{"regen_time", INT32},
	{"level", INT32},
	{"stat_id", INT32},
	{"attack_range", INT32},
	{"attack_speed_type", INT32},
	{"hp", INT32},
	{"mp", INT32},
	{"attack_point", INT32},
	{"magic_point", INT32},
	{"defence", INT32},
	{"magic_defence", INT32},
	{"attack_speed", INT32},
	{"magic_speed", INT32},
	{"accuracy", INT32},
	{"avoid", INT32},
	{"magic_accuracy", INT32},
	{"magic_avoid", INT32},
	{"ai_script", STRING, length=256},
	{"contact_script", STRING, length=256},
	{"texture_group", INT32},
	{"type", BYTE } -- 7.3 relating to maps 
}