tableName = "QuestResource"
fileName = "db_quest(ascii).rdb"

fields = 
{
	{ "id", INT32 },	
	{ "text_id_quest", INT32 },
	{ "text_id_summary", INT32 },
	{ "text_id_status", INT32 },	
	{ "limit_begin_time", INT32 },
	{ "limit_end_time", INT32 },
	{ "limit_level", INT32 },
	{ "limit_job_level", INT32 },
	{ "limit_max_level", INT32 },
	{ "limit_max_job_level", INT32 },	
	{"limit_bits", BIT_VECTOR, show=0 },
	{"limit_deva", BIT_FROM_VECTOR, dependency="limit_bits", bit_position=2},
	{"limit_asura", BIT_FROM_VECTOR, dependency="limit_bits", bit_position=3},
	{"limit_gaia", BIT_FROM_VECTOR, dependency="limit_bits", bit_position=4},
	{"limit_fighter", BIT_FROM_VECTOR, dependency="limit_bits", bit_position=5},
	{"limit_hunter", BIT_FROM_VECTOR, dependency="limit_bits", bit_position=6},
	{"limit_magician", BIT_FROM_VECTOR, dependency="limit_bits", bit_position=7},
	{"limit_summoner", BIT_FROM_VECTOR, dependency="limit_bits", bit_position=8},
	{ "limit_job", INT32 },
	{ "limit_favor", INT32 },	
	{ "repeatable", INT32 }, -- bool bIsRepeatable;	
	{ "invoke_condition", INT32 },
	{ "invoke_value", INT32 },	
	{ "time_limit_type_bits", BIT_VECTOR, show=0 },
	{ "time_limit_type", BIT_FROM_VECTOR, dependency="time_limit_type_bits", bit_position=32},
	{ "time_limit", INT32 },	
	{ "type", INT32 }, -- QuestType (is enum, int value)	
	{ "value1", INT32 },
	{ "value2", INT32 },
	{ "value3", INT32 },
	{ "value4", INT32 },
	{ "value5", INT32 },
	{ "value6", INT32 },
	{ "value7", INT32 },
	{ "value8", INT32 },
	{ "value9", INT32 },
	{ "value10", INT32 },
	{ "value11", INT32 },
	{ "value12", INT32 },	
	{ "drop_group_id", INT32 },	
	{ "quest_difficulty", INT32 },	
	{ "favor", INT32 },
	{ "exp", INT32 },
	{ "jp", INT32 },
	{ "holicpoint", INT32 },
	{ "gold", INT32 },	
    { "default_reward_id", INT32 },
    { "default_reward_level", INT32 },
    { "default_reward_quantity", INT32 },	
    { "optional_reward_id1", INT32 },
    { "optional_reward_level1", INT32 },
    { "optional_reward_quantity1", INT32 },	
    { "optional_reward_id2", INT32 },
    { "optional_reward_level2", INT32 },
    { "optional_reward_quantity2", INT32 },	
    { "optional_reward_id3", INT32 },
    { "optional_reward_level3", INT32 },
    { "optional_reward_quantity3", INT32 },	
    { "optional_reward_id4", INT32 },
    { "optional_reward_level4", INT32 },
    { "optional_reward_quantity4", INT32 },	
    { "optional_reward_id5", INT32 },
    { "optional_reward_level5", INT32 },
    { "optional_reward_quantity5", INT32 },	
    { "optional_reward_id6", INT32 },
    { "optional_reward_level6", INT32 },
    { "optional_reward_quantity6", INT32 },	
	{ "forequest1", INT32 },
	{ "forequest2", INT32 },
	{ "forequest3", INT32 },	
	{ "or_flag_bits", BIT_VECTOR, show=0 },
	{ "or_flag", BIT_FROM_VECTOR, dependency="or_flag_bits", bit_position=1}
}