tableName = "SkillStage"
fileName = "db_skillstage(ascii).rdb"

fields = {
	{"id", INT32 },
	{"elemental", BYTE },
	{"type", BYTE },
	{"deal_damage", BYTE },
	{"has_target", BYTE },
	{"corpse_target", BYTE },
	{"is_toggle", BYTE },
	{"unknown0", INT16, default=163, show=0},
	{"casting_time", SINGLE },
	{"is_creature_skill", INT16},
	{"unknown1", INT16, default=0, show=0},
	{"stage_type_id", INT32 },
	{"casting_type_id", INT32 },
	{"casting_start_motion_id", INT32 },
	{"casting_middle_motion_id", INT32 },
	{"casting_fx_set_id", INT32 },
	{"fire_motion_id", INT32 },
	{"fire_fx_set_id", INT32 },
	{"stage_data_01", SINGLE },
	{"stage_data_02", SINGLE },
	{"stage_data_03", SINGLE },
	{"stage_data_04", SINGLE },
	{"stage_data_05", SINGLE },
	{"stage_data_06", SINGLE },
	{"stage_data_07", SINGLE },
	{"stage_data_08", SINGLE },
	{"stage_data_09", SINGLE },
	{"stage_data_10", SINGLE },
	{"stage_data_11", SINGLE },
	{"stage_data_12", SINGLE },
	{"stage_data_13", SINGLE },
	{"stage_data_14", SINGLE },
	{"stage_data_15", SINGLE },
	{"stage_data_16", SINGLE },
	{"stage_data_17", SINGLE },
	{"stage_data_18", SINGLE },
	{"stage_data_19", SINGLE },
	{"stage_data_20", SINGLE },
	{"sub_stage_on_hit_id", INT32 },
	{"sub_stage_on_hit_continuous", INT32 },
	{"hit_fx_output_delay", INT32 },
	{"hit_fx_set_id", INT32 },
	{"hit_fx_set_position_id", INT32 },
	{"fire_fx_output_delay", INT32 },
	{"sub_fire_fx_set_id", INT32 },
	{"sub_fire_fx_position", INT32 }
}
