tableName = "StateResource"
fileName = "db_tenacity(ascii).rdb"

fields = 
{
	{ "state_id", INT32 },
	{ "text_id", INT32 },
	{ "tooltip_id", INT32 },
	{ "is_harmful", BYTE },
	{ "unknown", BYTE, length=3, show=0 },
	{ "state_time_type", INT32 },
	{ "state_group", INT32 },
	{ "duplicate_group_1", INT32 },
	{ "duplicate_group_2", INT32 },
	{ "duplicate_group_3", INT32 },
	{ "uf_avatar", BYTE },
	{ "uf_summon", BYTE },
	{ "uf_monster", BYTE },
	{ "unknown1", BYTE, length=1, show=0 },
	{ "base_effect_id", INT32 },
	{ "fire_interval", INT32 },
	{ "elemental_type", INT32 },
	{ "amplify_base", SINGLE },
	{ "amplify_per_skl", SINGLE },
	{ "add_damage_base", INT32 },
	{ "add_damage_per_skl", INT32 },
	{ "effect_type", INT32 },
	{ "value_0", DOUBLE },
	{ "value_1", DOUBLE },
	{ "value_2", DOUBLE },
	{ "value_3", DOUBLE },
	{ "value_4", DOUBLE },
	{ "value_5", DOUBLE },
	{ "value_6", DOUBLE },
	{ "value_7", DOUBLE },
	{ "value_8", DOUBLE },
	{ "value_9", DOUBLE },
	{ "value_10", DOUBLE },
	{ "value_11", DOUBLE },
	{ "value_12", DOUBLE },
	{ "value_13", DOUBLE },
	{ "value_14", DOUBLE },
	{ "value_15", DOUBLE },
	{ "value_16", DOUBLE },
	{ "value_17", DOUBLE },
	{ "value_18", DOUBLE },
	{ "value_19", DOUBLE },
	{ "icon_id", INT32 },
	{ "icon_file_name", STRING, length=256 },
	{ "fx_id", INT32 },
	{ "pos_id", INT32 },
	{ "cast_skill_id", INT32 },
	{ "cast_fx_id", INT32 },
	{ "cast_fx_pos_id", INT32 },
	{ "hit_fx_id", INT32 },
	{ "hit_fx_pos_id", INT32 },
	{ "special_output_timing_id", INT32 },
	{ "special_output_fx_id", INT32 },
	{ "special_output_fx_pos_id", INT32 },
	{ "special_output_fx_delay", INT32 },
	{ "state_fx_id", INT32 },
	{ "state_fx_pos_id", INT32 }
}