tableName = "SummonResource"
fileName = "db_creature(ascii)"

fields = {
	{"id", INT32}, -- start SummonBase
	{"model_id", INT32},
	{"name_id", INT32},
	{"type", INT32},
	{"magic_type", INT32},
	{"rate", BYTE},
	{"stat_id", INT32},
	{"size", SINGLE},
	{"scale", SINGLE},
	{"target_fx_size", SINGLE},
	{"standard_walk_speed", INT32},
	{"standard_run_speed", INT32},
	{"riding_speed", INT32},
	{"run_speed", INT32},
	{"is_riding_only", BYTE},
	{"riding_motion_type", INT32},
	{"attack_range", INT32}, -- end SummonBase
	{"walk_type", INT32}, -- start _SUMMON_INFO_FILE : SummonBase
	{"slant_type", INT32},
	{"material", INT32},
	{"weapon_type", INT32},
	{"attack_motion_speed", INT32},
	{"form", INT32},
	{"evolve_target", INT32},
	{"camera_x", INT32},
	{"camera_y", INT32},
	{"camera_z", INT32},
	{"target_x", SINGLE},
	{"target_y", SINGLE},
	{"target_z", SINGLE},
	{"model", STRING, length=256},
	{"motion_file_id", INT32},
	{"face_id", INT32},
	{"face_file_name", STRING, length=256},
	{"card_id", INT32},
	{"illust_file_name", STRING, length=256},
	{"text_feature_id", INT32},
	{"text_name_id", INT32},
	{"skill1_id", INT32},
	{"skill1_text_id", INT32},
	{"skill2_id", INT32},
	{"skill2_text_id", INT32},
	{"skill3_id", INT32},
	{"skill3_text_id", INT32},
	{"skill4_id", INT32},
	{"skill4_text_id", INT32},
	{"skill5_id", INT32},
	{"skill5_text_id", INT32},
	{"texture_group", INT32},
	{"local_flag", INT32}, -- end _SUMMON_INFO_FILE	
}