rdb.fields = {
	{"motion_id", TYPE_INT32},
	{"race_id", TYPE_INT32},
	{"file_name", TYPE_CHAR, 48},
	{"frame_length", TYPE_INT32},
	{"play_speed", TYPE_INT32},
	{"graphic_effect_file_ID", TYPE_INT32},
	{"graphic_effect_speed_type", TYPE_INT32},
	{"graphic_effect_position", TYPE_INT32},
	{"sound_file_ID", TYPE_INT32},
	{"sound_volumn", TYPE_INT32},
	{"sound_play_probability", TYPE_INT32},
	{"sound_timing", TYPE_INT32},
	{"fx_id", TYPE_INT32},
	{"fx_timing", TYPE_INT32},
	{"fx_position", TYPE_INT32},
	{"fx_play_speed", TYPE_INT32},
	{"unkownvalue01", TYPE_INT32},
	{"event01_id", TYPE_INT16},
	{"event02_id", TYPE_INT16},
	{"event03_id", TYPE_INT16},
	{"event04_id", TYPE_INT16},
	{"event05_id", TYPE_INT16},
	{"event06_id", TYPE_INT16},
	{"event07_id", TYPE_INT16},
	{"event08_id", TYPE_INT16},
	{"event09_id", TYPE_INT16},
	{"event10_id", TYPE_INT16},
	{"event01_timing", TYPE_INT16},
	{"event02_timing", TYPE_INT16},
	{"event03_timing", TYPE_INT16},
	{"event04_timing", TYPE_INT16},
	{"event05_timing", TYPE_INT16},
	{"event06_timing", TYPE_INT16},
	{"event07_timing", TYPE_INT16},
	{"event08_timing", TYPE_INT16},
	{"event09_timing", TYPE_INT16},
	{"event10_timing", TYPE_INT16},
	{"graphic_effect_follow", TYPE_INT8},
	{"sound_reverb_apply", TYPE_INT8},
	{"sound_filter_apply", TYPE_INT8},
	{"sound_stereo_apply", TYPE_INT8},
}



rdb.defaultTableName = "CharacterMotion"

